### ISSUE TITLE
PFAChain enforcing order when combining input and output Records

### ISSUE THREAD

**Issue by patrick-boueri** [opendatagroup/hadrian#6]
https://github.com/opendatagroup/hadrian/blob/ad5b1f731593a2524abc2eabe647f9f07a32ce1c/titus/titus/producer/chain.py#L324 i think there's an issue with the zip and differently ordered Records

**Comment by jpivarski** [comment]
Although PFA uses Avro's schema resolution when receiving data (the input data's schema only needs to be Avro-compatible with the PFA's input declaration), this `pfachain` tool requires schemas at the boundaries to be exactly the same. That is, to make a PFA file of A -> B, A's output must be exactly the same as B's input, not just Avro-compatible. (Relaxing that constraint would complicate `pfachain`: it would have to insert conversions in cases where they're not exactly the same.)

One particularly benign form of two schemas being Avro-compatible is if the two have the same fields, but in a different order. The code you highlighted would reject that case (as it rejects any difference between A's output and B's input), though we could allow it without complicating `pfachain`. This kind of difference would not need any conversions.

To implement it, one would simply relax the constraint you're pointing to: verify that A's output fields are a superset of B's input fields, write the for loop over A's fields, rather than the zip, and use A to define the type globally. The PFA code does not need to be modified.

That's the how, but I don't see the why. "Any Avro-compatible difference" and "Must be exactly the same" are both easy policies to describe. Allowing permutations in record field order loosens the policy a little bit, but doesn't take it all the way to the other well-known policy. Is there a specific use-case for allowing this?

**Comment by patrick-boueri** [comment]
The policy requirements make sense and would warrant keeping it as needed. The use case was more for ease of use, but maintaining the policy and changing the record order internal to the corresponding PFAs should be the way to use pfachain (currently what is being done). Thanks Jim!
